### ISSUE TITLE
sosa:Result unsatisfiable in the new ssnx

### ISSUE THREAD

**Issue by maximelefrancois86** [w3c/sdw#998] opened 2018-01-17 09:48 UTC
There is an insatisfiability whose origin is hasResult.

In a nutshell, the axioms (1) and (2) are too strict and should be relaxed to (1') and (2') :

sosa:hasResult ≡ oldssn:hasValue (1)
sosa:hasResult ≡ oldssn:observationResult (2)

oldssn:hasValue ⊑ sosa:hasResult (1')
oldssn:observationResult ⊑ sosa:hasResult (2')

Axiom (1) is causing the following problem.
oldssn:hasValue is a sub-property of dul:hasRegion, whose range in DUL has dul:Abstract as a super-class.
Yet, a sosa:Sampling procedure have only sosa:Sample as a result, and sosa:Sample is a sub-class of ( dul:Event or dul:Object or dul:Quality ) 

Axiom (2) is causing a few problem that are non trivial, but basically it boils down to either:
 - disjunction between dul:SocialObject and dul:PhysicalObject .
 - disjunctions between dul:Event and dul:Object .

If one relaxes (1) into (1') and (2) into (2'), then the insatisfiability no longer holds.

**Comment by maximelefrancois86** [comment] 2018-02-20 08:29
implemented in PR #1000

**Comment by tidoust** [comment] 2018-03-09 08:47
Pull request merged. The issue is now fixed in the Editor's Draft. The published Recommendation cannot be directly updated but [a new entry was added to the Errata document](https://www.w3.org/2017/10/vocab-ssn-errata.html#entry-6)

**Closed by tidoust** 2018-03-09 08:47 UTC
Labels: ssn
